[Fixed Donate Page]
codeforsanjose/codeforsanjose.github.io pull request #78
Opened 2022-12-19 07:09 UTC by ErikaVasNormandy

- retied the donate button to the old webflow, apply,codeforsanjose.org/donate
- This is powered by donorbox, I suppose it must be a code for America thing?

### :scroll: Description
We need to decide if we want to keep this one or stay with the old url campaign one. Either way it seems as if people need to go through Code For America first

2022-12-22 08:07 UTC, sunnymui commented
Looks good to me, as long as we still have access to wherever that donorbox funds to

2022-12-22 15:49 UTC, JMStudiosJoe requested changes
remove commented out code, no need to keep it source control has it all

2022-12-22 16:43 UTC, ErikaVasNormandy commented
Applied the changes to remove commented out code

2022-12-26 16:32 UTC, JMStudiosJoe approved these changes

2022-12-26 16:41 UTC, merged